# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - model: timm_classifier
  - trainer: default
  - paths: default
  - hydra: default

  # experiment configs allow for version control of specific hyperparameters
  # e.g. best hyperparameters for given model and datamodule
  - experiment: dogbreed_experiment

  # debugging config (enable through command line, e.g. `python infer.py debug=default)
  - debug: null

# task name, determines output directory path
task_name: "infer"

# tags to help you identify your experiments
# you can overwrite this in experiment configs
# overwrite from command line with `python infer.py tags="[first_tag, second_tag]"`
tags: ["dogbreed", "inference"]

# seed for random number generators in pytorch, numpy and python.random
seed: null

# path to the checkpoint file to use for inference
# if null, the script will attempt to use the best checkpoint from training
ckpt_path: null

# Input and output directories for inference
paths:
  input_dir: ${paths.model_artifacts}/input_images
  output_dir: ${paths.model_artifacts}/predicted_images

# Number of images to process (set to null to process all images)
num_images: 10

# Image file extension to look for
image_extension: "*.jpg"